# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1466777601);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1466778144);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1466782227);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1466777481);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1466777361);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 27);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150917052249");
user_pref("browser.slowStartup.averageTime", 1630);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20150917052249");
user_pref("browser.startup.homepage_override.mstone", "38.3.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":0}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1466824173423");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1466737834743");
user_pref("datareporting.policy.firstRunTime", "1466737773422");
user_pref("datareporting.sessions.current.activeTicks", 35);
user_pref("datareporting.sessions.current.firstPaint", 606);
user_pref("datareporting.sessions.current.main", 60);
user_pref("datareporting.sessions.current.sessionRestored", 1002);
user_pref("datareporting.sessions.current.startTime", "1466784617577");
user_pref("datareporting.sessions.current.totalTime", 194);
user_pref("datareporting.sessions.currentIndex", 7);
user_pref("datareporting.sessions.previous.0", "{\"s\":1466737771100,\"a\":27,\"t\":168,\"c\":true,\"m\":1270,\"fp\":3259,\"sr\":3640}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1466777240640,\"a\":78,\"t\":417,\"c\":true,\"m\":90,\"fp\":1460,\"sr\":1599}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1466778022170,\"a\":54,\"t\":293,\"c\":true,\"m\":1271,\"fp\":3239,\"sr\":3576}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1466782106758,\"a\":25,\"t\":174,\"c\":true,\"m\":81,\"fp\":898,\"sr\":1481}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1466782458165,\"a\":45,\"t\":541,\"c\":true,\"m\":1360,\"fp\":3269,\"sr\":3849}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1466784422827,\"a\":10,\"t\":59,\"c\":true,\"m\":1621,\"fp\":3378,\"sr\":3901}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1466784490272,\"a\":11,\"t\":61,\"c\":true,\"m\":51,\"fp\":583,\"sr\":964}");
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:38.3.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1466777601);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "38.3.0");
user_pref("extensions.lastPlatformVersion", "38.3.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"38.3.0\",\"st\":1466736322000,\"mt\":1442482247000}}}");
user_pref("gecko.buildID", "20150917052249");
user_pref("gecko.mstone", "38.3.0");
user_pref("idle.lastDailyNotification", 1466784987);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1466737835);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20150917052249");
user_pref("media.gmp-manager.lastCheck", 1466737835);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1466784617);
user_pref("toolkit.telemetry.previousBuildID", "20150917052249");
